display_name: PlaneClash
package_name: PlaneClash
maintainer:
  name: chen08209
  email: chen08209@gmail.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator3-dev
  - libkeybinder-3.0-dev

keywords:
  - PlaneClash
  - Clash
  - ClashMeta
  - Proxy

generic_name: PlaneClash

categories:
  - Network

startup_notify: true