name: Build Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.2'
          channel: 'stable'
      
      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Build Windows
        run: flutter build windows --release
      
      - name: Upload raw artifact
        uses: actions/upload-artifact@v4
        with:
          name: PlaneClash-Windows-Portable
          path: build/windows/x64/runner/Release/
      
      - name: Install Inno Setup
        run: |
          choco install innosetup -y
      
      - name: Create Installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "windows\installer.iss"
      
      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: PlaneClash-Setup
          path: installer_output/PlaneClash_Setup.exe
